// Generated by delombok at Mon Jul 17 13:40:01 CEST 2023
package edu.uoc.elc.lti.platform;

import java.util.List;

/**
 * @author xaracil@uoc.edu
 */
public class NamesRoleServiceResponse {
	private String id;
	private List<Member> members;

	@java.lang.SuppressWarnings("all")
	public String getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	public List<Member> getMembers() {
		return this.members;
	}

	@java.lang.SuppressWarnings("all")
	public void setId(final String id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	public void setMembers(final List<Member> members) {
		this.members = members;
	}
}
