// Generated by delombok at Fri Jul 28 11:41:52 CEST 2023
package edu.uoc.elc.lti.platform.accesstoken;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author xaracil@uoc.edu
 */
public class AccessTokenResponse {
	private String scope;
	@JsonProperty("access_token")
	private String accessToken;
	@JsonProperty("token_type")
	private String tokenType;
	@JsonProperty("expires_in")
	private int expiresIn;

	@java.lang.SuppressWarnings("all")
	public String getScope() {
		return this.scope;
	}

	@java.lang.SuppressWarnings("all")
	public String getAccessToken() {
		return this.accessToken;
	}

	@java.lang.SuppressWarnings("all")
	public String getTokenType() {
		return this.tokenType;
	}

	@java.lang.SuppressWarnings("all")
	public int getExpiresIn() {
		return this.expiresIn;
	}
}
