// Generated by delombok at Fri Jul 28 11:41:52 CEST 2023
package edu.uoc.elc.lti.tool.validator;

import edu.uoc.lti.MessageTypesEnum;

/**
 * @author xaracil@uoc.edu
 */
public enum MessageTypesValidatorEnum {
	LTI_RESOURCE_LINK(MessageTypesEnum.LtiResourceLinkRequest.name(), new LTIResourceLinkLaunchValidatable()), DEEP_LINKING(MessageTypesEnum.LtiDeepLinkingRequest.name(), new DeepLinkingLaunchValidatable());
	private final String messageType;
	private final LaunchValidatable validator;

	public static LaunchValidatable getValidator(String name) {
		for (MessageTypesValidatorEnum messageTypesValidator : values()) {
			if (messageTypesValidator.getMessageType().equals(name)) {
				return messageTypesValidator.getValidator();
			}
		}
		return null;
	}

	@java.lang.SuppressWarnings("all")
	private MessageTypesValidatorEnum(final String messageType, final LaunchValidatable validator) {
		this.messageType = messageType;
		this.validator = validator;
	}

	@java.lang.SuppressWarnings("all")
	public String getMessageType() {
		return this.messageType;
	}

	@java.lang.SuppressWarnings("all")
	public LaunchValidatable getValidator() {
		return this.validator;
	}
}
