// Generated by delombok at Fri Jul 28 11:45:02 CEST 2023
package edu.uoc.lti.jwt.claims;

import java.util.List;
import java.util.Map;

/**
 * @author xaracil@uoc.edu
 */
public class TestLaunch {
	private final String name;
	private final Map<String, Object> header;
	private final Map<String, Object> payload;
	private final List<String> specialFieldsToKeepFromPayload;

	@java.lang.SuppressWarnings("all")
	public TestLaunch(final String name, final Map<String, Object> header, final Map<String, Object> payload, final List<String> specialFieldsToKeepFromPayload) {
		this.name = name;
		this.header = header;
		this.payload = payload;
		this.specialFieldsToKeepFromPayload = specialFieldsToKeepFromPayload;
	}

	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}

	@java.lang.SuppressWarnings("all")
	public Map<String, Object> getHeader() {
		return this.header;
	}

	@java.lang.SuppressWarnings("all")
	public Map<String, Object> getPayload() {
		return this.payload;
	}

	@java.lang.SuppressWarnings("all")
	public List<String> getSpecialFieldsToKeepFromPayload() {
		return this.specialFieldsToKeepFromPayload;
	}
}
