// Generated by delombok at Fri Jul 28 11:41:52 CEST 2023
package edu.uoc.elc.lti.tool;

import java.util.List;

/**
 * @author xaracil@uoc.edu
 */
public class AssignmentGradeService {
	private List<String> scope;
	private String lineitems;
	private String lineitem;

	public boolean canReadResults() {
		return scope != null && scope.contains(ScopeEnum.AGS_SCOPE_RESULT.getScope());
	}

	public boolean canReadLineItems() {
		return canManageLineItems() || (scope != null && scope.contains(ScopeEnum.AGS_SCOPE_LINE_ITEM_READONLY.getScope()));
	}

	public boolean canManageLineItems() {
		return scope != null && scope.contains(ScopeEnum.AGS_SCOPE_LINE_ITEM.getScope());
	}

	public boolean canScore() {
		return scope != null && scope.contains(ScopeEnum.AGS_SCOPE_SCORE.getScope());
	}

	@java.lang.SuppressWarnings("all")
	public List<String> getScope() {
		return this.scope;
	}

	@java.lang.SuppressWarnings("all")
	public String getLineitems() {
		return this.lineitems;
	}

	@java.lang.SuppressWarnings("all")
	public String getLineitem() {
		return this.lineitem;
	}

	@java.lang.SuppressWarnings("all")
	public void setScope(final List<String> scope) {
		this.scope = scope;
	}

	@java.lang.SuppressWarnings("all")
	public void setLineitems(final String lineitems) {
		this.lineitems = lineitems;
	}

	@java.lang.SuppressWarnings("all")
	public void setLineitem(final String lineitem) {
		this.lineitem = lineitem;
	}
}
