// Generated by delombok at Mon Jul 17 13:40:01 CEST 2023
package edu.uoc.elc.lti.tool;

import java.util.List;

/**
 * @author xaracil@uoc.edu
 */
public class Context {
	private String id;
	private String label;
	private String title;
	private List<String> type;

	@java.lang.SuppressWarnings("all")
	public String getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	public String getLabel() {
		return this.label;
	}

	@java.lang.SuppressWarnings("all")
	public String getTitle() {
		return this.title;
	}

	@java.lang.SuppressWarnings("all")
	public List<String> getType() {
		return this.type;
	}

	@java.lang.SuppressWarnings("all")
	public void setId(final String id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	public void setLabel(final String label) {
		this.label = label;
	}

	@java.lang.SuppressWarnings("all")
	public void setTitle(final String title) {
		this.title = title;
	}

	@java.lang.SuppressWarnings("all")
	public void setType(final List<String> type) {
		this.type = type;
	}
}
