// Generated by delombok at Fri Jul 28 11:41:52 CEST 2023
package edu.uoc.elc.lti.tool;

/**
 * Universitat Oberta de Catalunya
 * Made for the project lti-13
 */
public class Deployment {
	private String deploymentId;

	@java.lang.SuppressWarnings("all")
	Deployment(final String deploymentId) {
		this.deploymentId = deploymentId;
	}


	@java.lang.SuppressWarnings("all")
	public static class DeploymentBuilder {
		@java.lang.SuppressWarnings("all")
		private String deploymentId;

		@java.lang.SuppressWarnings("all")
		DeploymentBuilder() {
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Deployment.DeploymentBuilder deploymentId(final String deploymentId) {
			this.deploymentId = deploymentId;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		public Deployment build() {
			return new Deployment(this.deploymentId);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "Deployment.DeploymentBuilder(deploymentId=" + this.deploymentId + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	public static Deployment.DeploymentBuilder builder() {
		return new Deployment.DeploymentBuilder();
	}

	@java.lang.SuppressWarnings("all")
	public String getDeploymentId() {
		return this.deploymentId;
	}

	@java.lang.SuppressWarnings("all")
	public void setDeploymentId(final String deploymentId) {
		this.deploymentId = deploymentId;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Deployment)) return false;
		final Deployment other = (Deployment) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$deploymentId = this.getDeploymentId();
		final java.lang.Object other$deploymentId = other.getDeploymentId();
		if (this$deploymentId == null ? other$deploymentId != null : !this$deploymentId.equals(other$deploymentId)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Deployment;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $deploymentId = this.getDeploymentId();
		result = result * PRIME + ($deploymentId == null ? 43 : $deploymentId.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Deployment(deploymentId=" + this.getDeploymentId() + ")";
	}
}
