// Generated by delombok at Fri Jul 28 11:41:52 CEST 2023
package edu.uoc.elc.lti.tool;

import java.util.List;

/**
 * @author xaracil@uoc.edu
 */
public class NamesRoleService {
	private String context_memberships_url;
	private List<String> service_versions;

	@java.lang.SuppressWarnings("all")
	public String getContext_memberships_url() {
		return this.context_memberships_url;
	}

	@java.lang.SuppressWarnings("all")
	public List<String> getService_versions() {
		return this.service_versions;
	}

	@java.lang.SuppressWarnings("all")
	public void setContext_memberships_url(final String context_memberships_url) {
		this.context_memberships_url = context_memberships_url;
	}

	@java.lang.SuppressWarnings("all")
	public void setService_versions(final List<String> service_versions) {
		this.service_versions = service_versions;
	}
}
