// Generated by delombok at Mon Jul 17 13:40:01 CEST 2023
package edu.uoc.elc.lti.tool;

/**
 * @author xaracil@uoc.edu
 */
public class Platform {
	private String guid;
	private String name;
	private String contact_email;
	private String description;
	private String url;
	private String product_family_code;
	private String version;

	@java.lang.SuppressWarnings("all")
	public String getGuid() {
		return this.guid;
	}

	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}

	@java.lang.SuppressWarnings("all")
	public String getContact_email() {
		return this.contact_email;
	}

	@java.lang.SuppressWarnings("all")
	public String getDescription() {
		return this.description;
	}

	@java.lang.SuppressWarnings("all")
	public String getUrl() {
		return this.url;
	}

	@java.lang.SuppressWarnings("all")
	public String getProduct_family_code() {
		return this.product_family_code;
	}

	@java.lang.SuppressWarnings("all")
	public String getVersion() {
		return this.version;
	}

	@java.lang.SuppressWarnings("all")
	public void setGuid(final String guid) {
		this.guid = guid;
	}

	@java.lang.SuppressWarnings("all")
	public void setName(final String name) {
		this.name = name;
	}

	@java.lang.SuppressWarnings("all")
	public void setContact_email(final String contact_email) {
		this.contact_email = contact_email;
	}

	@java.lang.SuppressWarnings("all")
	public void setDescription(final String description) {
		this.description = description;
	}

	@java.lang.SuppressWarnings("all")
	public void setUrl(final String url) {
		this.url = url;
	}

	@java.lang.SuppressWarnings("all")
	public void setProduct_family_code(final String product_family_code) {
		this.product_family_code = product_family_code;
	}

	@java.lang.SuppressWarnings("all")
	public void setVersion(final String version) {
		this.version = version;
	}
}
