// Generated by delombok at Mon Jul 17 13:40:01 CEST 2023
package edu.uoc.elc.lti.tool;

import java.util.List;
import java.util.Objects;

/**
 * @author xaracil@uoc.edu
 */
public class Registration {
	private String id;
	private String clientId;
	private String name;
	private String platform;
	private String keySetUrl;
	private String accessTokenUrl;
	private String oidcAuthUrl;
	private KeySet keySet;
	private List<Deployment> deployments;

	public Deployment getDeployment(String deploymentId) {
		return Objects.nonNull(deployments) ? deployments.stream().filter(deployment -> deployment.getDeploymentId().equals(deploymentId)).findFirst().orElse(null) : null;
	}

	@java.lang.SuppressWarnings("all")
	Registration(final String id, final String clientId, final String name, final String platform, final String keySetUrl, final String accessTokenUrl, final String oidcAuthUrl, final KeySet keySet, final List<Deployment> deployments) {
		this.id = id;
		this.clientId = clientId;
		this.name = name;
		this.platform = platform;
		this.keySetUrl = keySetUrl;
		this.accessTokenUrl = accessTokenUrl;
		this.oidcAuthUrl = oidcAuthUrl;
		this.keySet = keySet;
		this.deployments = deployments;
	}


	@java.lang.SuppressWarnings("all")
	public static class RegistrationBuilder {
		@java.lang.SuppressWarnings("all")
		private String id;
		@java.lang.SuppressWarnings("all")
		private String clientId;
		@java.lang.SuppressWarnings("all")
		private String name;
		@java.lang.SuppressWarnings("all")
		private String platform;
		@java.lang.SuppressWarnings("all")
		private String keySetUrl;
		@java.lang.SuppressWarnings("all")
		private String accessTokenUrl;
		@java.lang.SuppressWarnings("all")
		private String oidcAuthUrl;
		@java.lang.SuppressWarnings("all")
		private KeySet keySet;
		@java.lang.SuppressWarnings("all")
		private List<Deployment> deployments;

		@java.lang.SuppressWarnings("all")
		RegistrationBuilder() {
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Registration.RegistrationBuilder id(final String id) {
			this.id = id;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Registration.RegistrationBuilder clientId(final String clientId) {
			this.clientId = clientId;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Registration.RegistrationBuilder name(final String name) {
			this.name = name;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Registration.RegistrationBuilder platform(final String platform) {
			this.platform = platform;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Registration.RegistrationBuilder keySetUrl(final String keySetUrl) {
			this.keySetUrl = keySetUrl;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Registration.RegistrationBuilder accessTokenUrl(final String accessTokenUrl) {
			this.accessTokenUrl = accessTokenUrl;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Registration.RegistrationBuilder oidcAuthUrl(final String oidcAuthUrl) {
			this.oidcAuthUrl = oidcAuthUrl;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Registration.RegistrationBuilder keySet(final KeySet keySet) {
			this.keySet = keySet;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Registration.RegistrationBuilder deployments(final List<Deployment> deployments) {
			this.deployments = deployments;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		public Registration build() {
			return new Registration(this.id, this.clientId, this.name, this.platform, this.keySetUrl, this.accessTokenUrl, this.oidcAuthUrl, this.keySet, this.deployments);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "Registration.RegistrationBuilder(id=" + this.id + ", clientId=" + this.clientId + ", name=" + this.name + ", platform=" + this.platform + ", keySetUrl=" + this.keySetUrl + ", accessTokenUrl=" + this.accessTokenUrl + ", oidcAuthUrl=" + this.oidcAuthUrl + ", keySet=" + this.keySet + ", deployments=" + this.deployments + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	public static Registration.RegistrationBuilder builder() {
		return new Registration.RegistrationBuilder();
	}

	@java.lang.SuppressWarnings("all")
	public String getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	public String getClientId() {
		return this.clientId;
	}

	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}

	@java.lang.SuppressWarnings("all")
	public String getPlatform() {
		return this.platform;
	}

	@java.lang.SuppressWarnings("all")
	public String getKeySetUrl() {
		return this.keySetUrl;
	}

	@java.lang.SuppressWarnings("all")
	public String getAccessTokenUrl() {
		return this.accessTokenUrl;
	}

	@java.lang.SuppressWarnings("all")
	public String getOidcAuthUrl() {
		return this.oidcAuthUrl;
	}

	@java.lang.SuppressWarnings("all")
	public KeySet getKeySet() {
		return this.keySet;
	}

	@java.lang.SuppressWarnings("all")
	public List<Deployment> getDeployments() {
		return this.deployments;
	}
}
