// Generated by delombok at Mon Jul 17 13:40:01 CEST 2023
package edu.uoc.elc.lti.tool;

/**
 * @author xaracil@uoc.edu
 */
public class ResourceLink {
	private String id;
	private String title;
	private String description;

	@java.lang.SuppressWarnings("all")
	public String getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	public String getTitle() {
		return this.title;
	}

	@java.lang.SuppressWarnings("all")
	public String getDescription() {
		return this.description;
	}

	@java.lang.SuppressWarnings("all")
	public void setId(final String id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	public void setTitle(final String title) {
		this.title = title;
	}

	@java.lang.SuppressWarnings("all")
	public void setDescription(final String description) {
		this.description = description;
	}
}
