// Generated by delombok at Fri Jul 28 11:41:52 CEST 2023
package edu.uoc.elc.lti.tool;

import edu.uoc.lti.accesstoken.AccessTokenRequestBuilder;
import edu.uoc.lti.clientcredentials.ClientCredentialsTokenBuilder;
import edu.uoc.lti.deeplink.DeepLinkingTokenBuilder;

/**
 * @author xaracil@uoc.edu
 */
public class ToolBuilders {
	private final ClientCredentialsTokenBuilder clientCredentialsTokenBuilder;
	private final AccessTokenRequestBuilder accessTokenRequestBuilder;
	private final DeepLinkingTokenBuilder deepLinkingTokenBuilder;

	@java.lang.SuppressWarnings("all")
	public ToolBuilders(final ClientCredentialsTokenBuilder clientCredentialsTokenBuilder, final AccessTokenRequestBuilder accessTokenRequestBuilder, final DeepLinkingTokenBuilder deepLinkingTokenBuilder) {
		this.clientCredentialsTokenBuilder = clientCredentialsTokenBuilder;
		this.accessTokenRequestBuilder = accessTokenRequestBuilder;
		this.deepLinkingTokenBuilder = deepLinkingTokenBuilder;
	}

	@java.lang.SuppressWarnings("all")
	public ClientCredentialsTokenBuilder getClientCredentialsTokenBuilder() {
		return this.clientCredentialsTokenBuilder;
	}

	@java.lang.SuppressWarnings("all")
	public AccessTokenRequestBuilder getAccessTokenRequestBuilder() {
		return this.accessTokenRequestBuilder;
	}

	@java.lang.SuppressWarnings("all")
	public DeepLinkingTokenBuilder getDeepLinkingTokenBuilder() {
		return this.deepLinkingTokenBuilder;
	}
}
