// Generated by delombok at Mon Jul 17 13:40:01 CEST 2023
package edu.uoc.elc.lti.tool;

/**
 * @author xaracil@uoc.edu
 */
public class User {
	private String id;
	private String givenName;
	private String familyName;
	private String middleName;
	private String picture;
	private String email;
	private String name;

	@java.lang.SuppressWarnings("all")
	User(final String id, final String givenName, final String familyName, final String middleName, final String picture, final String email, final String name) {
		this.id = id;
		this.givenName = givenName;
		this.familyName = familyName;
		this.middleName = middleName;
		this.picture = picture;
		this.email = email;
		this.name = name;
	}


	@java.lang.SuppressWarnings("all")
	public static class UserBuilder {
		@java.lang.SuppressWarnings("all")
		private String id;
		@java.lang.SuppressWarnings("all")
		private String givenName;
		@java.lang.SuppressWarnings("all")
		private String familyName;
		@java.lang.SuppressWarnings("all")
		private String middleName;
		@java.lang.SuppressWarnings("all")
		private String picture;
		@java.lang.SuppressWarnings("all")
		private String email;
		@java.lang.SuppressWarnings("all")
		private String name;

		@java.lang.SuppressWarnings("all")
		UserBuilder() {
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public User.UserBuilder id(final String id) {
			this.id = id;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public User.UserBuilder givenName(final String givenName) {
			this.givenName = givenName;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public User.UserBuilder familyName(final String familyName) {
			this.familyName = familyName;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public User.UserBuilder middleName(final String middleName) {
			this.middleName = middleName;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public User.UserBuilder picture(final String picture) {
			this.picture = picture;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public User.UserBuilder email(final String email) {
			this.email = email;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public User.UserBuilder name(final String name) {
			this.name = name;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		public User build() {
			return new User(this.id, this.givenName, this.familyName, this.middleName, this.picture, this.email, this.name);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "User.UserBuilder(id=" + this.id + ", givenName=" + this.givenName + ", familyName=" + this.familyName + ", middleName=" + this.middleName + ", picture=" + this.picture + ", email=" + this.email + ", name=" + this.name + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	public static User.UserBuilder builder() {
		return new User.UserBuilder();
	}

	@java.lang.SuppressWarnings("all")
	public String getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	public String getGivenName() {
		return this.givenName;
	}

	@java.lang.SuppressWarnings("all")
	public String getFamilyName() {
		return this.familyName;
	}

	@java.lang.SuppressWarnings("all")
	public String getMiddleName() {
		return this.middleName;
	}

	@java.lang.SuppressWarnings("all")
	public String getPicture() {
		return this.picture;
	}

	@java.lang.SuppressWarnings("all")
	public String getEmail() {
		return this.email;
	}

	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}

	@java.lang.SuppressWarnings("all")
	public void setId(final String id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	public void setGivenName(final String givenName) {
		this.givenName = givenName;
	}

	@java.lang.SuppressWarnings("all")
	public void setFamilyName(final String familyName) {
		this.familyName = familyName;
	}

	@java.lang.SuppressWarnings("all")
	public void setMiddleName(final String middleName) {
		this.middleName = middleName;
	}

	@java.lang.SuppressWarnings("all")
	public void setPicture(final String picture) {
		this.picture = picture;
	}

	@java.lang.SuppressWarnings("all")
	public void setEmail(final String email) {
		this.email = email;
	}

	@java.lang.SuppressWarnings("all")
	public void setName(final String name) {
		this.name = name;
	}
}
