// Generated by delombok at Fri Jul 28 11:41:52 CEST 2023
package edu.uoc.elc.lti.platform.ags;

import java.util.List;

import edu.uoc.elc.lti.exception.UnauthorizedAgsCallException;
import edu.uoc.lti.ags.Result;
import edu.uoc.lti.ags.ResultServiceClient;

/**
 * @author xaracil@uoc.edu
 */
public class GenericResultServiceClient {
	private final boolean canRead;
	private final ResultServiceClient resultServiceClient;

	public List<Result> getLineItemResults(String id, Integer limit, Integer page, String userId) {
		if (!canRead) {
			throw new UnauthorizedAgsCallException("getLineItemResults");
		}
		return resultServiceClient.getLineItemResults(id, limit, page, userId);
	}

	@java.lang.SuppressWarnings("all")
	public GenericResultServiceClient(final boolean canRead, final ResultServiceClient resultServiceClient) {
		this.canRead = canRead;
		this.resultServiceClient = resultServiceClient;
	}
}
