// Generated by delombok at Fri Jul 28 11:41:52 CEST 2023
package edu.uoc.elc.lti.platform.ags;

import edu.uoc.elc.lti.exception.UnauthorizedAgsCallException;
import edu.uoc.lti.ags.Score;
import edu.uoc.lti.ags.ScoreServiceClient;

/**
 * @author xaracil@uoc.edu
 */
public class GenericScoreServiceClient {
	private final boolean canScore;
	private final ScoreServiceClient scoreServiceClient;

	public boolean score(String lineItemId, Score score) {
		if (!canScore) {
			throw new UnauthorizedAgsCallException("score");
		}
		return scoreServiceClient.score(lineItemId, score);
	}

	@java.lang.SuppressWarnings("all")
	public GenericScoreServiceClient(final boolean canScore, final ScoreServiceClient scoreServiceClient) {
		this.canScore = canScore;
		this.scoreServiceClient = scoreServiceClient;
	}
}
