// Generated by delombok at Mon Jul 17 13:40:01 CEST 2023
package edu.uoc.elc.lti.platform.deeplinking;

import java.util.List;

import edu.uoc.elc.lti.tool.deeplinking.Settings;
import edu.uoc.lti.deeplink.content.Item;

/**
 * @author xaracil@uoc.edu
 */
public class ItemValidator {
	final Settings settings;
	String message;

	public boolean isValid(Item item) {
		if (!accessTypeIsValid(item.getType())) {
			message = "Platform doesn\'t allow content items of type " + item.getType();
			return false;
		}
		return true;
	}

	private boolean accessTypeIsValid(String type) {
		return settings.getAccept_types().contains(type);
	}

	protected boolean documentTargetIsValid(String presentation) {
		final List<String> acceptPresentationDocumentTargets = settings.getAccept_presentation_document_targets();
		return (acceptPresentationDocumentTargets != null && acceptPresentationDocumentTargets.size() > 0 ? acceptPresentationDocumentTargets.contains(presentation) : true);
	}

	@java.lang.SuppressWarnings("all")
	public ItemValidator(final Settings settings) {
		this.settings = settings;
	}

	@java.lang.SuppressWarnings("all")
	public String getMessage() {
		return this.message;
	}
}
